### ISSUE TITLE
How to run and Configure WebUI Locally. No response from server? Critical issue...Please resolve Soom

### ISSUE THREAD

**Issue by prabhu66** [Azure/pcs-remote-monitoring-webui#1011]
Hi,
I have cloned pcs-remote-monitoring-webui.
i have given npm install and i have started we app using npm start in localhost:3000
But there is no response in the server.

How to link microservices in this web app. Please resolve this as soon as possible.

![response error](https://user-images.githubusercontent.com/18692829/40050770-0dd93492-5856-11e8-8b01-4e6bdba1852a.png)

**Comment by dvescovi1** [comment]
same issue here ...please help

**Comment by Smarker** [comment]
same issue for me, too

**Comment by jillcary** [comment]
Hello, 
In order to see data on the dashboard of the webui, you will need to run the other microservices against deployed Azure resources.

There are a few ways to do this, the easiest is way is by following the instructions here: https://docs.microsoft.com/azure/iot-accelerators/iot-accelerators-remote-monitoring-customize 

If you would like to run locally with a minimum number of cloud resources you can follow the skightly-more local setup involved instructions here, running services locally with Docker.
https://docs.microsoft.com/azure/iot-accelerators/iot-accelerators-remote-monitoring-deploy-local 

Let us know if you have any additional questions.

**Comment by dvescovi1** [comment]
I was able to finally get some data.
The device location/map does not render correctly.
Both the Alerts and Analytics still show "No data available"  even when Alert should have trigger (by using the Increase Pressure device method.

Also several tiles do not render correctly in IE but in Chrome they do show correctly. There seems to be some kind of justification issue with the text on some tiles under IE.

**Comment by prabhu66** [comment]
You should start Stream Analytics Manually in azure portal @dvescovi1 . Once you run docker-compose up, thn stop that command and then goto portal and run stream analytics job manually then you can see data in UI.

**Comment by zhang-hua** [comment]
@prabhu66 , To start and output alarms, Azure Streaming Job is dependent on Cosmos DB & Collections which have to be created by ASA manager service. StreamAnalytics RP did not support creating DB & Collections in ARM template for now. So this manual step is required for setting up local development environment. But it is not required for cloud deployment because an extra step is in place to try starting streaming job in PCS CLI and solution accelerator for cloud deployment after all of the containers is spinning up.

**Comment by zhang-hua** [comment]
@Smarker , that error is caused by reverse proxy server nginx which requires to read TLS certification from `/app/certs/tls.crt` which will mounted from host as volume of docker container.  [See here](https://github.com/Azure/azure-iot-pcs-remote-monitoring-dotnet/blob/master/reverse-proxy/content/nginx.conf#L38). What is your operating system? If it is Window, you can install `git-bash` which will give you a Linux like shell environment and you can generate certificate and key by using `ssh-keygen` and put them in `/app/certs/` with correct read permission. If you're using Linux system, it should be easier to generate certification and key files and put there.

**Comment by prabhu66** [comment]
@zhang-hua I know stream analytics will create cosmo db and collections. once you run docker-compose up, check in portal that stream analytics is in stop mode. You should run stream analytics manually. Then again give docker-compose up command, u can see the data in UI. I have tried, it is working perfectly.

**Comment by Smarker** [comment]
@zhang-hua I was running docker on windows and used the WSL for the linux-like environment. I will try generating a certificate and putting them into `/app/certs`. Thanks for the help!

**Comment by ppathan** [comment]
Fixed.

**Comment by pw007** [comment]
@Smarker ,how you generate the certificate and put them into /app/certs ? thanks.
