### ISSUE TITLE
Repo forks of external developers are not getting built in VSTS

### ISSUE THREAD

**Issue by isaac73** [Azure/pcs-remote-monitoring-webui#1128]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 

https://github.com/Azure/pcs-remote-monitoring-webui/pull/1123
 
The above PR did not get a build even after 3 days. After a brief investigation, I found that the branch is from a different fork in Github account.
Our repo -> https://github.com/Azure
Actual repo where is branch is at ->  https://github.com/dominicbetts

To mitigate, I manually triggered a build in VSTS referencing the PR number.
https://solutionaccelerators.visualstudio.com/RemoteMonitoring/RemoteMonitoring%20Team/_build/results?buildId=1809

I guess this issue could have sneaked in when we migrated from travis to VSTS.

**Comment by asdonald** [comment]
@sushilraje Will look into this.

**Comment by sushilraje** [comment]
@isaac73: This is a feature we have disabled on all of our builds. To enable - you can go to 
Build &rightarrow; Triggers, 
Under triggers, 
Enable Pull Request &rightarrow; Enable builds on Fork

Its not recommended though due to reasons mentioned [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/ci-public?view=vsts&tabs=github#validate-contributions-from-forks).

For you current build of webui, I have activated the build from fork, please disable it once you are done.
