### ISSUE TITLE
Creating a new rule, then editing it shows up twice on WebUI. 

### ISSUE THREAD

**Issue by asdonald** [Azure/pcs-remote-monitoring-webui#1162]
# Type of issue 

- [ ] Bug
- [ ] New feature
- [x] Enhancement

# Description 
Issue: 
When creating a new rule and then editing it created two rules that were exactly the same. I’m trying to repro it again.

Suggestions:
-	Let folks assign longer then 10 mins for alerts. 

...

# Steps to reproduce 

1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior 
...

# Current behavior 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch/tag: ...

# Screenshot

**Comment by mechaffin** [comment]
I believe this is by design.

After creating a rule, the flyout stays open so you can create another new rule. This allows the user to create rules with similar values (perhaps a warning level and a critical level) without having to open and close the flyout and retype a lot of similar information. So each time you click the "Apply" button on the New Rule flyout, you get a new rule.  It does NOT change into an edit flyout when you add the rule. That's by design.
