### ISSUE TITLE
Simulation status is showing error

### ISSUE THREAD

**Issue by ppathan** [Azure/pcs-remote-monitoring-webui#1237]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
Clicked on the settings on the Dashboard and saw that "Error loading simulation status"

# Steps to reproduce 

1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior 
Toggle button

# Current behavior 
None

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch/tag: ...

# Screenshot 
![image](https://user-images.githubusercontent.com/16170750/55114691-e09e3e80-509f-11e9-9c80-c280a3ea8217.png)

**Comment by elvinm** [comment]
It turns out a few more environment variables we thought were optional in device simulation are needed. Our frontend calls into device simulation and thus need cors whitelist and aad variables to be set. All of these items are already in keyvault so it just expanding on Sushil's PR for env variables.
