### ISSUE TITLE
getting cross-origin issues when running web ui locally.

### ISSUE THREAD

**Issue by sadeep24** [Azure/pcs-remote-monitoring-webui#1246]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
I'm trying to Prepare a local development environment for customize UI according to the article on [https://docs.microsoft.com/en-gb/azure/iot-accelerators/iot-accelerators-remote-monitoring-customize](url) . I have completed all the steps but when i  run web ui locally i'm getting cross origin issues.

# Steps to reproduce 

1.Prepare a local development environment for the UI according to the article [https://docs.microsoft.com/en-gb/azure/iot-accelerators/iot-accelerators-remote-monitoring-customize](url)

# Expected behavior 
...

# Current behavior 
...

# Possible solution 
...

# Context and Environment
* Operating System: Window 10
* GitHub branch/tag: ...

# Screenshot 
![Annotation 2019-06-17 144035](https://user-images.githubusercontent.com/18017108/59592642-120e2f80-910e-11e9-8d36-3e47f308edab.png)
![Annotation 2019-06-17 144129](https://user-images.githubusercontent.com/18017108/59592652-13d7f300-910e-11e9-8743-ae755f6e8ef9.png)

**Comment by elvinm** [comment]
This is likely a similar issue that is currently being fixed. https://github.com/Azure/pcs-cli/pull/513

If you want to try out the fix you basically need to edit your /app/auth.sh script that is in your VM to be the same as what you see in that pull request. 

Essentially the issue was that some parameters that need to be edited to allow local development when using --unsafe flag were not being set.

**Comment by sadeep24** [comment]
Thank you so much Elvin Morales it worked.
