### ISSUE TITLE
Opening the webapp see the dashboard before asked to login

### ISSUE THREAD

**Issue by CaitlinEsworthy** [Azure/pcs-remote-monitoring-webui#621]
# Type of issue

- [ ] Bug
- [ ] New feature
- [x] Improvement

# Description
Wasn't able to get a screenshot and not sure I can replicate OR if it is a problem, but is seems odd that I am sometimes able to see a glimpse of the dashboard before asked to login. Is it a security issue?

**Comment by dluc** [comment]
It's a known "issue" but not a security issue, because there is no user content in the application. You can this about the UI as a "Skype" application downloaded: you launch the app, you "see" the app, but you cannot access contacts and messages until after the authentication.

We should improve the UX not to show a "flash" of the app if the user is not authenticated yet.
